services:
  twitch-drops-miner:
    build: .
    image: vtstv/twitch-drops-miner:latest
    container_name: twitch-drops-miner
    restart: unless-stopped
    ports:
      - "28088:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - TZ=UTC
